<a href="https://colab.research.google.com/github/Armando122104/Titanic_Dataset/blob/main/Titanic_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Crear y leer datos

In [1]:
import pandas as pd

# Crear DataFrame desde diccionario
df = pd.DataFrame({
    'nombre': ['Ana', 'Luis', 'Mia'],
    'edad':   [28, 34, 22],
    'salario': [50000, 72000, 41000]
})

# Leer desde archivos
df = pd.read_csv('Titanic.csv')

##Exploración Rápida

In [2]:
df.head(10)           # Primeras 10 filas

,passengerId,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
8,8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False

In [3]:
df.tail(5)            # Últimas 5 filas

,passengerId,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
886,886,0,2,male,27.0,0,0,13.00,S,Second,man,True,NaN,Southampton,no,True
887,887,1,1,female,19.0,0,0,30.00,S,First,woman,False,B,Southampton,yes,True
888,888,0,3,female,NaN,1,2,23.45,S,Third,woman,False,NaN,Southampton,no,False
889,889,1,1,male,26.0,0,0,30.00,C,First,man,True,C,Cherbourg,yes,True
890,890,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True

In [4]:
df.shape              # (filas, columnas)

(891, 16)

In [5]:
df.dtypes             # Tipos de datos

passengerId      int64
survived         int64
pclass           int64
sex             object
age            float64
sibsp            int64
parch            int64
fare           float64
embarked        object
class           object
who             object
adult_male        bool
deck            object
embark_town     object
alive           object
alone             bool
dtype: object

In [6]:
df.info()              # Resumen completo

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   passengerId  891 non-null    int64
 1   survived     891 non-null    int64
 2   pclass       891 non-null    int64
 3   sex          891 non-null    object
 4   age          714 non-null    float64
 5   sibsp        891 non-null    int64
 6   parch        891 non-null    int64
 7   fare         891 non-null    float64
 8   embarked     889 non-null    object
 9   class        891 non-null    object
 10  who          891 non-null    object
 11  adult_male   891 non-null    bool
 12  deck         203 non-null    object
 13  embark_town  889 non-null    object
 14  alive        891 non-null    object
 15  alone        891 non-null    bool
dtypes: bool(2), float64(2), int64(5), object(7)
memory usage: 99.3+ KB

In [7]:
df.describe()          # Estadísticas numéricas

,passengerId,survived,pclass,age,sibsp,parch,fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,445.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,0.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,222.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,445.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,667.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,890.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [8]:
df.isnull().sum()      # Nulos por columna

passengerId      0
survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [9]:
df.nunique()           # Valores únicos

passengerId    891
survived         2
pclass           3
sex              2
age             88
sibsp            7
parch            7
fare           248
embarked         3
class            3
who              3
adult_male       2
deck             7
embark_town      3
alive            2
alone            2
dtype: int64

In [10]:
df.value_counts('survived') # Frecuencia de valores

survived
0    549
1    342
Name: count, dtype: int64

In [11]:
df.memory_usage(deep=True)  # Uso de memoria

Index            132
passengerId     7128
survived        7128
pclass          7128
sex            47851
age             7128
sibsp           7128
parch           7128
fare            7128
embarked       44514
class          48298
who            47040
adult_male       891
deck           32166
embark_town    52991
alive          45783
alone            891
dtype: int64

##Selección & Filtrado

In [12]:
# Selección de columnas
df['age']                 # Serie
df[['pclass', 'fare', 'survived']]      # Sub-DataFrame

# Filtrado condicional
df[df['age'] > 25]
df.query('age > 25 and fare >= 50')
df[df['sex'].isin(['male', 'female'])]

# Selección por posición / etiqueta
df.loc[0:5, 'survived':'fare']   # por label
df.iloc[0:5, [1, 3, 4]]              # por índice

# Selección con patrón (columnas que empiezan con 'p')
df.filter(regex='^p')

     passengerId  pclass  parch
0              0       3      0
1              1       1      0
2              2       3      0
3              3       1      0
4              4       3      0
..           ...     ...    ...
886          886       2      0
887          887       1      0
888          888       3      2
889          889       1      0
890          890       3      0

[891 rows x 3 columns]

##Limpieza de Datos

In [13]:
# Manejo de nulos
df.dropna(subset=['age'])
df['age'] = df['age'].fillna(df['age'].median())
df.fillna(df.ffill())
df.infer_objects(copy=False)

# Duplicados
df.drop_duplicates(subset=['passengerId'], keep='last')

# Tipos de datos
#df['fecha'] = pd.to_datetime(df['fecha']) Este dataset no tiene ninguna fecha
df['who'] = df['who'].astype('category')

# Renombrar y reemplazar
df.rename(columns={'pclass': 'passengerClass'}, inplace=True)
df['survived'] = df['survived'].replace({0: 'No', 1: 'Yes'})

df.head() # Para verque los cambios de haya reflejado

,passengerId,survived,passengerClass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,No,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,Yes,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,2,Yes,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,3,Yes,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,4,No,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

##Agrupación & Agregación

In [14]:
# Group By básico
df.groupby('sex')['fare'].mean() # Tafica promedio agrupada por sexo

sex
female    44.479818
male      25.523893
Name: fare, dtype: float64

In [15]:
# Múltiples agregaciones
df.groupby('passengerClass').agg(
    edad_promedio = ('age', 'mean'),
    tarifa_max    = ('fare', 'max'),
    total_pasajeros = ('passengerId', 'count')
)

                edad_promedio  tarifa_max  total_pasajeros
passengerClass
1                   36.812130    512.3292              216
2                   29.765380     73.5000              184
3                   25.932627     69.5500              491

In [16]:
# Pivot Table
pd.pivot_table(df,  # Suma (sum) todas las tarifas de todos los pasajeros que tengan la misma classe (class)
    index='embark_town',    # y que embarcaron en la misma ciudad
    values='fare',
    columns='class',
    aggfunc='sum'
)

class            First     Second      Third
embark_town
Cherbourg    8901.0750   431.0917   740.1295
Queenstown    180.0000    37.0500   805.2043
Southampton  8936.3375  3333.7000  5169.3613

In [17]:
# Crosstab
pd.crosstab(df['embark_town'], df['who'])         # Es un contador de los valores en comun de filas y columnas

who          child  man  woman
embark_town
Cherbourg       18   90     60
Queenstown       5   37     35
Southampton     60  410    174

##Joins & Merge

In [18]:
# Dataframe creado para poder hacer la operacion al no exitir dos tablas
class_desc = pd.DataFrame({
    'passengerClass': [1, 2, 3],
    'class_name': ['Primera', 'Segunda', 'Tercera']
})

# Merge (SQL-style)
pd.merge(df, class_desc,
    left_on='passengerClass',
    right_on='passengerClass',
    how='left'          # left | right | outer | cross
)

,passengerId,survived,passengerClass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,class_name
0,0,No,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,Tercera
1,1,Yes,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,Primera
2,2,Yes,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,Tercera
3,3,Yes,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,Primera
4,4,No,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,Tercera
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,886,No,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,Segunda
887,887,Yes,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,Primera
888,888,No,3,female,28.0,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,Tercera
889,889,Yes,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,Primera
890,890,No,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,Tercera

In [19]:
# Concatenar DataFrames
pd.concat([df, class_desc], axis=0)  # vertical
pd.concat([df, class_desc], axis=1)  # horizontal

# Join por índice
df.join(class_desc.set_index('passengerClass'), on='passengerClass', how='inner')

,passengerId,survived,passengerClass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,class_name
0,0,No,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,Tercera
1,1,Yes,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,Primera
2,2,Yes,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,Tercera
3,3,Yes,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,Primera
4,4,No,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,Tercera
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,886,No,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,Segunda
887,887,Yes,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,Primera
888,888,No,3,female,28.0,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,Tercera
889,889,Yes,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,Primera
890,890,No,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,Tercera

##Tranformaciones

In [20]:
# Apply: funciones custom
df['who_upper'] = df['who'].apply(lambda x: str(x).upper())
df['rango_tarifa'] = df['fare'].apply(
    lambda x: 'alto' if x > 50 else 'bajo'
)

# --- Window Functions ---
df['rolling_fare'] = df['fare'].rolling(7).mean() # Media móvil de tarifa
df['fare_cum_sum'] = df['fare'].cumsum()          # Suma acumulada de ingresos
df['fare_pct_change'] = df['fare'].pct_change()   # Cambio porcentual entre registros
df['rank_fare'] = df['fare'].rank(ascending=False)# Ranking de quién pagó más

df

,passengerId,survived,passengerClass,sex,age,sibsp,parch,fare,embarked,class,...,deck,embark_town,alive,alone,who_upper,rango_tarifa,rolling_fare,fare_cum_sum,fare_pct_change,rank_fare
0,0,No,3,male,22.0,1,0,7.2500,S,Third,...,NaN,Southampton,no,False,MAN,bajo,NaN,7.2500,NaN,815.0
1,1,Yes,1,female,38.0,1,0,71.2833,C,First,...,C,Cherbourg,yes,False,WOMAN,alto,NaN,78.5333,8.832179,103.0
2,2,Yes,3,female,26.0,0,0,7.9250,S,Third,...,NaN,Southampton,yes,True,WOMAN,bajo,NaN,86.4583,-0.888824,659.5
3,3,Yes,1,female,35.0,1,0,53.1000,S,First,...,C,Southampton,yes,False,WOMAN,alto,NaN,139.5583,5.700315,144.0
4,4,No,3,male,35.0,0,0,8.0500,S,Third,...,NaN,Southampton,no,True,MAN,bajo,NaN,147.6083,-0.848399,628.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,886,No,2,male,27.0,0,0,13.0000,S,Second,...,NaN,Southampton,no,True,MAN,bajo,14.869643,28602.7493,-0.553648,484.5
887,887,Yes,1,female,19.0,0,0,30.0000,S,First,...,B,Southampton,yes,True,WOMAN,bajo,15.441071,28632.7493,1.307692,237.5
888,888,No,3,female,28.0,1,2,23.4500,S,Third,...,NaN,Southampton,no,False,WOMAN,bajo,17.663100,28656.1993,-0.218333,345.5
889,889,Yes,1,male,26.0,0,0,30.0000,C,First,...,C,Cherbourg,yes,True,MAN,bajo,20.446429,28686.1993,0.279318,237.5
890,890,No,3,male,32.0,0,0,7.7500,Q,Third,...,NaN,Queenstown,no,True,MAN,bajo,20.053571,28693.9493,-0.741667,768.5

In [21]:
def limpiar_datos(df):
    return df.dropna(subset=['age'])

def agregar_features(df):
    df['FamilySize'] = df['sibsp'] + df['parch'] + 1
    return df

def filtrar_outliers(df):
    return df[df['fare'] > 300]

# Pipe: encadenar transformaciones
result = (df
    .pipe(limpiar_datos)
    .pipe(agregar_features)
    .pipe(filtrar_outliers)
)

result

,passengerId,survived,passengerClass,sex,age,sibsp,parch,fare,embarked,class,...,embark_town,alive,alone,who_upper,rango_tarifa,rolling_fare,fare_cum_sum,fare_pct_change,rank_fare,FamilySize
258,258,Yes,1,female,35.0,0,0,512.3292,C,First,...,Cherbourg,yes,True,WOMAN,alto,108.019643,7420.7539,4.922881,2.0,1
679,679,Yes,1,male,36.0,0,1,512.3292,C,First,...,Cherbourg,yes,False,MAN,alto,85.413700,21755.2245,9.923864,2.0,2
737,737,Yes,1,male,35.0,0,0,512.3292,C,First,...,Cherbourg,yes,True,MAN,alto,86.798814,24499.6329,13.904122,2.0,1

##Exportar & Optimizar

In [23]:
# Exportar
df.to_csv('Titanic_procesado.csv', index=False)
df.to_parquet('Titanic_procesado.parquet')

# Optimización de memoria
df['passengerClass'] = df['passengerClass'].astype('int8')
df['embarked'] = df['embarked'].astype('category')
df['sex'] = df['sex'].astype('category')

# Procesamiento por chunks (archivos grandes)
for chunk in pd.read_csv('Titanic.csv', chunksize=100):
    # Edad promedio de cada 100 datos
    print(chunk['age'].mean())

# Parquet con particiones
df.to_parquet('output_Titanic/', partition_cols=['alive'])

df_alive = pd.read_parquet('output_Titanic/alive=yes/')
print(df_alive)

27.46576923076923
28.549382716049383
30.753012048192772
27.85525
31.417763157894736
32.80921052631579
31.558641975308642
28.715487804878048
28.275974025974026
     passengerId survived  passengerClass     sex   age  sibsp  parch  \
0              1      Yes               1  female  38.0      1      0
1              2      Yes               3  female  26.0      0      0
2              3      Yes               1  female  35.0      1      0
3              8      Yes               3  female  27.0      0      2
4              9      Yes               2  female  14.0      1      0
..           ...      ...             ...     ...   ...    ...    ...
679          875      Yes               3  female  15.0      0      0
680          879      Yes               1  female  56.0      0      1
681          880      Yes               2  female  25.0      0      1
682          887      Yes               1  female  19.0      0      0
683          889      Yes               1    male  26.0      0      0

        fare embarked   class  ... adult_male  deck  embark_town  alone  \
0    71.2833        C   First  ...      False     C    Cherbourg  False
1     7.9250        S   Third  ...      False  None  Southampton   True
2    53.1000        S   First  ...      False     C  Southampton  False
3    11.1333        S   Third  ...      False  None  Southampton  False
4    30.0708        C  Second  ...      False  None    Cherbourg  False
..       ...      ...     ...  ...        ...   ...          ...    ...
679   7.2250        C   Third  ...      False  None    Cherbourg   True
680  83.1583        C   First  ...      False     C    Cherbourg  False
681  26.0000        S  Second  ...      False  None  Southampton  False
682  30.0000        S   First  ...      False     B  Southampton   True
683  30.0000        C   First  ...       True     C    Cherbourg   True

     who_upper rango_tarifa rolling_fare  fare_cum_sum  fare_pct_change  \
0        WOMAN         alto          NaN       78.5333         8.832179
1        WOMAN         bajo          NaN       86.4583        -0.888824
2        WOMAN         alto          NaN      139.5583         5.700315
3        WOMAN         bajo    23.086300      240.1374        -0.471730
4        CHILD         bajo    26.249986      270.2082         1.700978
..         ...          ...          ...           ...              ...
679      CHILD         bajo    16.686900    28389.8661        -0.698958
680      WOMAN         alto    21.288671    28498.6618         9.531966
681      WOMAN         bajo    23.717243    28524.6618        -0.687343
682      WOMAN         bajo    15.441071    28632.7493         1.307692
683        MAN         bajo    20.446429    28686.1993         0.279318

     rank_fare
0        103.0
1        659.5
2        144.0
3        526.0
4        233.5
..         ...
679      842.5
680       70.0
681      311.0
682      237.5
683      237.5

[684 rows x 21 columns]